name: Deploy to Amazon S3

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1                       # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: taginspo                    # set this to your Amazon ECR repository name
  ECS_SERVICE: service-taginspo             # set this to your Amazon ECS service name
  ECS_CLUSTER: cluster-taginspo                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: .aws/task-definition.json # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: container-taginspo           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Node.js Setup
      uses: actions/setup-node@v1
      with:
        node-version: ${{ secrets.NODE_VERSION}}

    - name: Dependency Installation
      run: npm install

    - name: App Build
      run: cd ./client && npm install && npm run build

    - name: Deploy to AWS S3
      run: aws s3 sync ./client/dist ${{ secrets.REACT_S3_BUCKET }} --delete